version: 2.1

# Tested these commands locally with Docker Desktop. To test locally, run this command:
# docker run -it -v [location of The-Feed code on your pc]:/home/circleci/project circleci/node:erbium-bullseye-browsers-legacy

# Define an executor
executors:
  docker_executor:
    docker:
      - image: circleci/node:erbium-bullseye-browsers-legacy

jobs:
  build:
    executor: docker_executor
    steps:
      - checkout
      # If latest node is required
      #- run:
      #    name: Installing Node
      #    command: |
      #      curl -fsSL https://deb.nodesource.com/setup_22.x -o nodesource_setup.sh
      #      sudo -E bash nodesource_setup.sh
      #      sudo apt-get install -y nodejs
      - run:
          name: Compile Code
          # Compile just the regular program and the program with Catch2
          command: |
            g++ -Werror src/*.cpp -o /home/circleci/project/the_feed.exe
            g++ -Werror src/*.cpp test/*.cpp test/catch/*.cpp -o /home/circleci/project/the_feed_test.exe
      # Allows "build" environment to persist into the "test" phase
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - the_feed_test.exe
  test:
    executor: docker_executor
    steps:
      - attach_workspace:
          at: /home/circleci/project/
      - run:
          name: Run Code
          command: '/home/circleci/project/the_feed_test.exe'


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build